
<table cellspacing="0" border="0"
	style="table-layout: fixed; width: 100%;" summary="">
	<thead>
		<tr>
			<td><a href="<?php echo $base_url . '?page='.GENERAL_PAGE?>"
				target="section_frame"><?php echo _("isp_general")?></a>&nbsp;&nbsp; 
				<a href="<?php echo $base_url . '?page='.PASSWORD_PAGE?>"
				target="section_frame"><?php echo _("isp_pass")?></a>&nbsp;&nbsp; 
				<a href="<?php echo $base_url . '?page='.FETCHMAIL_PAGE?>"
				target="section_frame"><?php echo _("isp_fetchmail")?></a>&nbsp;&nbsp; 
				<a href="<?php echo $base_url . '?page='.FORWARDING_PAGE?>"
				target="section_frame"><?php echo _("isp_forward")?></a>&nbsp;&nbsp; 
				<a href="<?php echo $base_url . '?page='.AUTOREPLY_PAGE?>"
				target="section_frame"><?php echo _("isp_autoreply")?></a>&nbsp;&nbsp; 
				<a href="<?php echo $base_url . '?page='.MAILFILTER_PAGE?>"
				target="section_frame"><?php echo _("isp_filter")?></a>&nbsp;&nbsp; 
				<a href="<?php echo $base_url . '?page='.POLICY_PAGE?>"
				target="section_frame"><?php echo _("isp_policy")?></a>&nbsp;&nbsp; 
				<a href="<?php echo $base_url . '?page='.WBLIST_PAGE?>"
				target="section_frame"><?php echo _("isp_wblist")?></a>
			</td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td style="height: 550px;"><iframe name="section_frame" width="100%"
				height="100%" frameborder="0" src="<?php echo $url?>"
				style="border: 1px solid <?php echo $color[14]?>"></iframe></td>
		</tr>
	</tbody>
</table>