<?php include_once ('templates/section_head.phtml'); ?>

<script type="text/javascript">
function isvalid() 
{
 var newp=document.passform._newpasswd;
 var conp=document.passform._confpasswd;
 
 if (newp.length < <?php echo $pwl?>) {
	  alert("<?php echo sprintf(_('passwordminlength'), $pwl)?>");
	  return false;
 }

 if (newp.value != conp.value) {
	  alert("<?php echo _('passwordinconsistency')?>");
	  return false;
 }
 
 return true;
}
</script>

<div id="prefs-title" class="boxtitle"><?php echo _("acc_pass")?></div>
<form name="passform" onsubmit="isvalid();"
	action="<?php echo SM_PATH . 'plugins/ispconfig3/ispconfig3.php?page='.PASSWORD_PAGE?>" method="post">
<div id="prefs-details">
<fieldset><legend><?php echo _("acc_pass")?> ::: <?php echo $username?></legend> <br />
<table>

	<tbody>
	<?php 
	if ($confirm) {
	?>
		<tr>
			<td class="title"><label for="curpasswd"><?php echo _("curpasswd")?>:</label></td>
			<td><input name="_curpasswd" id="curpasswd" size="20" type="password"></td>
		</tr>
	<?php } ?>
		<tr>
			<td class="title"><label for="newpasswd"><?php echo _("newpasswd")?>:</label></td>
			<td><input name="_newpasswd" id="newpasswd" size="20" type="password"></td>
		</tr>
		<tr>
			<td class="title"><label for="confpasswd"><?php echo _("confpasswd")?>:</label></td>
			<td><input name="_confpasswd" id="confpasswd" size="20"
				type="password"></td>
		</tr>

	</tbody>
</table>
<br />
</fieldset>
</div>

<div id="formfooter">
<div class="footerleft"><input value="<?php echo $save?>" type="submit" /></div>
</div>
</form>

<?php include_once ('templates/section_footer.phtml'); ?>