<?php include_once ('templates/section_head.phtml'); ?>

<div id="prefs-title" class="boxtitle"><?php echo _('isp_policy')?></div>
<div id="prefs-details">
<form name="policyform" action="<?php echo SM_PATH . 'plugins/ispconfig3/ispconfig3.php?page='.POLICY_PAGE?>" method="post">
<input name="_id" type="hidden" value="<?php echo $id?>" />
<fieldset><legend><?php echo _('isp_policy')?> ::: <?php echo $username?></legend> <br />
<?php 
if (empty($policy['policy_name'])) {
	echo '<div style="margin-left: 5px;">'._("nopolicy").'</div>';
} 
else {
?>
<table summary="" border="0" cellpadding="3">
	<tbody>
		<tr>
			<td class="title"><?php echo _("junkpolicy_name")?>:</td>
			<td class="">
			<select name="_policy" id="policy">
			<?php
			foreach ($entries as $entry)
			{
				if ($entry['policy_name'] == $policy['policy_name']) {
	                echo '<option value="' . $entry['id'] .'" selected="selected">'.$entry['policy_name'].'</option>' . "\n";
	            } else {
	                echo '<option value="' . $entry['id'] .'">'.$entry['policy_name'].'</option>' . "\n";
	            }
			}
			?>
			</select>			
			</td>
		</tr>
		<tr>
			<td class="title"><label for="spammove"><?php echo _("spammove")?></label>:</td>
			<td class=""><input name="_spammove" id="spammove" value="1" <?php echo $spammove?> type="checkbox" /></td>
		</tr>
	</tbody>
</table>
<br />
<?php } ?>
<div class="footerleft">
<input value="<?php echo $save?>" type="submit" />
</div>
</fieldset>

</form>
<fieldset><legend><?php echo _('policy_entries')?> ::: <?php echo $username?></legend> <br />
<div id="policies-cont">
<table id="policies-table" class="records-table" summary="" border="0" cellspacing="0">
	<thead>
		<tr>
			<td width="330px"><?php echo _('junkpolicy_name')?></td>
			<td width="60px"><?php echo _('junktaglevel')?></td>
			<td width="60px"><?php echo _('junkkilllevel')?></td>
		</tr>
	</thead>
	<tbody>
	<?php
	if(count($entries) == 0)
	{
		echo '<tr style="background:'.$color[4].';">
		<td colspan="3">'._('nofetch').'</td>
		</tr>';	
	} 
	else
	{
		foreach ($entries as $entry)
		{
			echo '<tr style="background:'.$color[4].';">
			<td>'.$entry['policy_name'].'</td>
			<td>'.$entry['spam_tag_level'].'</td>
			<td>'.$entry['spam_kill_level'].'</td>
			</tr>';
		}
	}
	?>
	</tbody>
</table>
</div>
<br>
</fieldset>

</div>

<?php include_once ('templates/section_footer.phtml'); ?>